<?php 


/**
 * Implementation of hook_form_alter.
 * We modify field form to add an option to multi field 
 */
function ia_multifields_form_alter(&$form, $form_state, $form_id) {
  // We're looking for the form of field that are valid 
  // multiple filefield 
  // multipe nodereference field 
  $valid_fields = array ('filefield');
  
  // If we are in the edit form of in a valid field
  if ($form_id === 'content_field_edit_form'  && isset($form['#field']) && (in_array ($form['#field']['module'], $valid_fields))) {
    dsm("the form is valid");
    
    // We define the new form element
    $form['field']['ia_multifields'] = array(
      '#type' => 'checkbox',
      '#title' => 'Hide empty multifields',
      '#weight' => 10,
      '#default_value' => variable_get('ia_multifields_' . $form['#field']['field_name'] , 0),
    );
    
    
    // We add a new validation function 
    $form['#submit'][] = '_ia_multifields_content_form_submit';
    
    // Application of the settings
    /* How to do ?
    J'ai peut etre trouver il faut que j'aille chercher mes variables, decoupes le nom du champs, et verifie si les champs en question existe dans le formulaire d'édition en cours ?
    if ($form['#id'] == 'node-form') {
      $simplify_fields= db_result(db_query("SELECT * FROM {variables} tn WHERE tn.tid = %d", $tid));
      ?>
    }
    */
  }
}  

/**
 * Stores ia_mutifields settings from content form.
 */
function _ia_multifields_content_form_submit($form, &$form_state) {
  variable_set('ia_multifields_'. $form['#field']['field_name'], $form_state['values']['ia_multifields']);
  return TRUE;
}




// A faire
// Declencher la fonction _ia_multiplefields_simplify sur un formulaire de node 
// Où un champs est utilisé configuré est utilisé
